name: movie_task
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter_screenutil: ^5.9.0
  intl: ^0.17.0
  path_provider: ^2.1.1
  http: ^1.1.0
  fluttertoast: ^8.2.2
  hive: ^2.2.3
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  cached_network_image: ^3.3.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

